ERROR 2024-11-19 10:51:55,048 views Missing key in translation response: 'French'
ERROR 2024-11-19 10:51:55,052 log Internal Server Error: /translate/
ERROR 2024-11-19 10:51:55,052 basehttp "POST /translate/ HTTP/1.1" 500 58
ERROR 2024-11-19 10:51:55,052 basehttp "POST /translate/ HTTP/1.1" 500 58
ERROR 2024-11-19 10:52:09,431 views Missing key in translation response: 'French'
ERROR 2024-11-19 10:52:09,433 log Internal Server Error: /translate/
ERROR 2024-11-19 10:52:09,434 basehttp "POST /translate/ HTTP/1.1" 500 58
ERROR 2024-11-19 10:52:09,434 basehttp "POST /translate/ HTTP/1.1" 500 58
ERROR 2024-11-19 10:52:17,799 views Missing key in translation response: 'Spanish'
ERROR 2024-11-19 10:52:17,801 log Internal Server Error: /translate/
ERROR 2024-11-19 10:52:17,801 basehttp "POST /translate/ HTTP/1.1" 500 59
ERROR 2024-11-19 10:52:17,801 basehttp "POST /translate/ HTTP/1.1" 500 59
ERROR 2024-11-19 11:10:35,708 log Internal Server Error: /profile_info/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:35,710 log Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:35,711 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:35,711 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:35,711 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:35,711 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:35,738 log Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:35,740 log Internal Server Error: /profile_info/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:35,743 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:35,743 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:35,743 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:35,743 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:39,164 log Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:39,173 log Internal Server Error: /profile_info/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:39,173 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:39,173 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:39,175 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:39,175 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:39,199 log Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:39,215 log Internal Server Error: /profile_info/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:39,215 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:39,215 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:39,216 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:39,216 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:40,371 log Internal Server Error: /profile_info/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:40,380 log Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:40,380 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:40,380 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:40,380 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:40,380 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:40,404 log Internal Server Error: /profile_info/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:40,412 log Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:40,413 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:40,413 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:40,413 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:40,413 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:41,623 log Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:41,631 log Internal Server Error: /profile_info/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:41,632 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:41,632 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:41,633 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:41,633 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:41,656 log Internal Server Error: /profile_info/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:41,663 log Internal Server Error: /profile/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework_simplejwt/authentication.py", line 130, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:41,664 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:41,664 basehttp "GET /profile_info/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183938
ERROR 2024-11-19 11:10:41,664 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:41,664 basehttp "GET /profile/?encrypted_content=didhCXecmWfpw0a1xvM9nYyAiSSqwNmAqIhxNgatHkim3TeZyb4AnJjFQMpN%2BN5l HTTP/1.1" 500 183977
ERROR 2024-11-19 11:10:55,071 log Internal Server Error: /get_user_services/esptest1@yopmail.com/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/core/views.py", line 1454, in get_user_services
    user = get_object_or_404(User, email=email)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:55,072 basehttp "GET /get_user_services/esptest1@yopmail.com/ HTTP/1.1" 500 134911
ERROR 2024-11-19 11:10:55,072 basehttp "GET /get_user_services/esptest1@yopmail.com/ HTTP/1.1" 500 134911
ERROR 2024-11-19 11:10:55,105 log Internal Server Error: /get_user_services/esptest1@yopmail.com/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/core/views.py", line 1454, in get_user_services
    user = get_object_or_404(User, email=email)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:55,106 basehttp "GET /get_user_services/esptest1@yopmail.com/ HTTP/1.1" 500 134911
ERROR 2024-11-19 11:10:55,106 basehttp "GET /get_user_services/esptest1@yopmail.com/ HTTP/1.1" 500 134911
ERROR 2024-11-19 11:10:55,108 log Internal Server Error: /get_cart/
ERROR 2024-11-19 11:10:55,113 log Internal Server Error: /get_cart/
ERROR 2024-11-19 11:10:55,114 basehttp "GET /get_cart/?email=esptest1%40yopmail.com HTTP/1.1" 500 136
ERROR 2024-11-19 11:10:55,114 basehttp "GET /get_cart/?email=esptest1%40yopmail.com HTTP/1.1" 500 136
ERROR 2024-11-19 11:10:55,119 basehttp "GET /get_cart/?email=esptest1%40yopmail.com HTTP/1.1" 500 136
ERROR 2024-11-19 11:10:55,119 basehttp "GET /get_cart/?email=esptest1%40yopmail.com HTTP/1.1" 500 136
ERROR 2024-11-19 11:10:55,135 log Internal Server Error: /get_user_services/esptest1@yopmail.com/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/core/views.py", line 1454, in get_user_services
    user = get_object_or_404(User, email=email)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:55,136 basehttp "GET /get_user_services/esptest1%40yopmail.com/ HTTP/1.1" 500 135055
ERROR 2024-11-19 11:10:55,136 basehttp "GET /get_user_services/esptest1%40yopmail.com/ HTTP/1.1" 500 135055
ERROR 2024-11-19 11:10:55,156 log Internal Server Error: /get_user_services/esptest1@yopmail.com/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/core/views.py", line 1454, in get_user_services
    user = get_object_or_404(User, email=email)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 296, in get_select
    sql, params = self.compile(col)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 546, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/expressions.py", line 1180, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 537, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:10:55,156 basehttp "GET /get_user_services/esptest1%40yopmail.com/ HTTP/1.1" 500 135055
ERROR 2024-11-19 11:10:55,156 basehttp "GET /get_user_services/esptest1%40yopmail.com/ HTTP/1.1" 500 135055
ERROR 2024-11-19 11:11:01,073 views Internal server error: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:11:01,074 log Internal Server Error: /session_logout/
ERROR 2024-11-19 11:11:01,074 basehttp "POST /session_logout/ HTTP/1.1" 500 34
ERROR 2024-11-19 11:11:01,074 basehttp "POST /session_logout/ HTTP/1.1" 500 34
ERROR 2024-11-19 11:11:06,082 views Internal server error: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:11:06,083 log Internal Server Error: /signin/
ERROR 2024-11-19 11:11:06,083 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2024-11-19 11:11:06,083 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2024-11-19 11:11:14,797 views Internal server error: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2024-11-19 11:11:14,798 log Internal Server Error: /signin/
ERROR 2024-11-19 11:11:14,799 basehttp "POST /signin/ HTTP/1.1" 500 34
ERROR 2024-11-19 11:11:14,799 basehttp "POST /signin/ HTTP/1.1" 500 34
