ERROR 2024-11-24 14:40:24,811 log Internal Server Error: /profile_android/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2117, in get_prep_value
    return int(value)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/contrib/auth/models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/core/views.py", line 5909, in profile_android
    profile = Profile.objects.get(user=user)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x1301239a0>.
ERROR 2024-11-24 14:40:24,814 basehttp "GET /profile_android/ HTTP/1.1" 500 166548
ERROR 2024-11-24 14:40:24,814 basehttp "GET /profile_android/ HTTP/1.1" 500 166548
ERROR 2024-11-25 05:58:58,899 views Unexpected error: [Errno 2] No such file or directory: './unique_domains.csv'
ERROR 2024-11-25 05:58:58,901 log Internal Server Error: /add_user/
ERROR 2024-11-25 05:58:58,901 basehttp "POST /add_user/ HTTP/1.1" 500 72
ERROR 2024-11-25 05:58:58,901 basehttp "POST /add_user/ HTTP/1.1" 500 72
ERROR 2024-11-25 06:34:25,580 log Internal Server Error: /guest_send_otp/
ERROR 2024-11-25 06:34:25,581 basehttp "POST /guest_send_otp/ HTTP/1.1" 500 65
ERROR 2024-11-25 06:34:25,581 basehttp "POST /guest_send_otp/ HTTP/1.1" 500 65
ERROR 2024-11-25 06:37:44,770 log Internal Server Error: /guest_send_otp/
ERROR 2024-11-25 06:37:44,771 basehttp "POST /guest_send_otp/ HTTP/1.1" 500 72
ERROR 2024-11-25 06:37:44,771 basehttp "POST /guest_send_otp/ HTTP/1.1" 500 72
ERROR 2024-11-25 10:47:42,295 log Internal Server Error: /profile_android/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2117, in get_prep_value
    return int(value)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/contrib/auth/models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/core/views.py", line 5911, in profile_android
    profile = Profile.objects.get(user=user)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x1509723e0>.
ERROR 2024-11-25 10:47:42,298 basehttp "GET /profile_android/ HTTP/1.1" 500 166548
ERROR 2024-11-25 10:47:42,298 basehttp "GET /profile_android/ HTTP/1.1" 500 166548
ERROR 2024-11-25 11:05:11,823 log Internal Server Error: /profile_android/
Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2117, in get_prep_value
    return int(value)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/contrib/auth/models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/core/views.py", line 5911, in profile_android
    profile = Profile.objects.get(user=user)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/fields/related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/Users/abhinavsaxena/Desktop/Esprit/ProdigiDesk/ProdigiD_Full_BE/env/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2119, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x150b35750>.
ERROR 2024-11-25 11:05:11,825 basehttp "GET /profile_android/ HTTP/1.1" 500 166548
ERROR 2024-11-25 11:05:11,825 basehttp "GET /profile_android/ HTTP/1.1" 500 166548
ERROR 2024-11-25 11:29:42,313 views Error during logout: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x12f751840>>.
ERROR 2024-11-25 11:29:42,314 log Internal Server Error: /logout_view_android/
ERROR 2024-11-25 11:29:42,315 basehttp "POST /logout_view_android/ HTTP/1.1" 500 45
ERROR 2024-11-25 11:29:42,315 basehttp "POST /logout_view_android/ HTTP/1.1" 500 45
